// config.h
// Single source of truth for all tunable constants and pin assignments.
// No magic numbers should appear anywhere else in the codebase hopefully
 
#pragma once
 
#include <cstdint>
 
namespace Config {
 

// Loop rates (Hz) — scheduler.cpp derives timer periods from these

namespace Rates {
    constexpr uint32_t IMU_HZ        = 1000;
    constexpr uint32_t CONTROL_HZ    = 500;
    constexpr uint32_t BARO_HZ       = 50;
    constexpr uint32_t LOG_HZ        = 100;
    constexpr uint32_t STATUS_HZ     = 10;
}
 

// PID gains — separate tuning for pitch and yaw in case of asymmetry

namespace PID {
    // Pitch axis
    constexpr float PITCH_KP = 2.5f;
    constexpr float PITCH_KI = 0.15f;
    constexpr float PITCH_KD = 0.35f;
 
    // Yaw axis
    constexpr float YAW_KP = 2.5f;
    constexpr float YAW_KI = 0.15f;
    constexpr float YAW_KD = 0.35f;
 
    // Anti-windup: clamp integral term contribution (in output units, degrees)
    constexpr float INTEGRAL_LIMIT_DEG = 8.0f;
 
    // Output limiting (final servo commanded deflection, degrees)
    constexpr float OUTPUT_LIMIT_DEG = 12.0f;
}
 

// Servo geometry / max limits?

namespace Servo {
    constexpr float MIN_DEFLECTION_DEG     = -12.0f;
    constexpr float MAX_DEFLECTION_DEG     =  12.0f;
    constexpr float CENTER_DEFLECTION_DEG  =   0.0f;
 
    // Max change per control update (deg) — prevents violent servo slew
    constexpr float MAX_RATE_DEG_PER_UPDATE = 1.5f;
 
    // PWM pulse width (microseconds) at min/center/max deflection.
    // Calibrate these against your actual servo horn/linkage geometry.
    constexpr uint16_t PWM_MIN_US    = 1000;
    constexpr uint16_t PWM_CENTER_US = 1500;
    constexpr uint16_t PWM_MAX_US    = 2000;
 
    constexpr uint16_t PWM_PERIOD_US = 20000; // 50 Hz servo frame
}
 

// Flight state machine thresholds

namespace Flight {
    // Launch detection: sustained acceleration above this (m/s^2, in body Z)
    // for LAUNCH_ACCEL_DURATION_MS confirms liftoff (avoids false trigger from handling/vibration on the pad).
    constexpr float LAUNCH_ACCEL_THRESHOLD_MPS2 = 25.0f; // ~2.5 g
    constexpr uint32_t LAUNCH_ACCEL_DURATION_MS = 100;
 
    // Burnout / start of coast: acceleration drops below this after having been in POWERED_ASCENT (m/s^2). Near-zero acceleration
    constexpr float BURNOUT_ACCEL_THRESHOLD_MPS2 = 5.0f;
    constexpr uint32_t BURNOUT_CONFIRM_MS = 150;
 
    // Apogee: vertical velocity crosses from positive to negative, confirmed for this many consecutive ms to reject noise.
    constexpr uint32_t APOGEE_CONFIRM_MS = 200;
    constexpr float APOGEE_VELOCITY_THRESHOLD_MPS = 0.0f;
 
    // Landed: altitude change below this (meters) for LANDED_CONFIRM_MS
    constexpr float LANDED_ALT_DELTA_M = 1.0f;
    constexpr uint32_t LANDED_CONFIRM_MS = 3000;
 
    // Safety: TVC is only ever active during POWERED_ASCENT. Ground level reference altitude is captured at ARM time.
}
 

// Sensor fusion (Madgwick filter)

namespace AHRS {
    // Beta gain schedule — higher = trust accelerometer more (faster convergence, noisier). Lower = trust gyro more (smoother, drifts).
    constexpr float BETA_GROUND    = 0.8f;  // fast convergence while on pad
    constexpr float BETA_POWERED   = 0.03f; // accel contaminated by thrust
    constexpr float BETA_COAST     = 0.05f;
    constexpr float BETA_DESCENT   = 0.4f;
 
    constexpr float GYRO_SAMPLE_DT = 1.0f / Rates::IMU_HZ;
}
 

// Barometric altitude estimation

namespace Baro {
    constexpr float SEA_LEVEL_PRESSURE_HPA = 1013.25f;
    constexpr float BARO_SAMPLE_DT = 1.0f / Rates::BARO_HZ;
    // Low-pass filter coefficient for vertical velocity derivative (0-1, higher = less smoothing)
    constexpr float VELOCITY_LPF_ALPHA = 0.2f;
}
 

// Logging

namespace Logging {
    constexpr uint32_t BUFFER_SIZE_BYTES = 4096; 
    constexpr const char* LOG_FILENAME_PREFIX = "FLIGHT";
}
 

// Battery / power monitoring

namespace Power {
    constexpr float BATTERY_LOW_VOLTAGE   = 6.8f;  // 2S Li-ion low warning
    constexpr float BATTERY_CRITICAL_VOLTAGE = 6.4f;
    // ADC voltage divider ratio 
    constexpr float ADC_DIVIDER_RATIO = 3.0f;
    constexpr float ADC_VREF = 3.3f;
    constexpr uint16_t ADC_MAX_COUNTS = 4095; // 12-bit ADC
}
 
// Watchdog

namespace Watchdog {
    constexpr uint32_t TIMEOUT_MS = 500;
}
 
// ---------------------------------------------------------------------
// Pin / peripheral map
// NOTE: these are placeholders following STM32 HAL naming. Will replace with the actual GPIO ports/pins and peripheral handles generated by CubeMX .ioc once 
// assigned, then re-point sensors.cpp /

// ---------------------------------------------------------------------
namespace Pins {
    // SPI bus for ICM-45686
    constexpr uint8_t IMU_CS_PIN = 0;      // placeholder, e.g. GPIO_PIN_4 on GPIOA
 
    // I2C BMP580 
    constexpr uint8_t BARO_ADDR = 0x47;    // BMP580 default 7-bit address (SDO high)
 
    // Servo PWM channels (TIMx_CHy)
    constexpr uint8_t SERVO_PITCH_CHANNEL = 1;
    constexpr uint8_t SERVO_YAW_CHANNEL   = 2;
 
    // Pyro channel MOSFET gate pins (4 channels assumed)
    constexpr uint8_t PYRO_CHANNEL_COUNT = 4;
 
    // WS2812 status LED — driven via TIM PWM + DMA
    constexpr uint8_t STATUS_LED_COUNT = 1;
 
    // Battery voltage ADC channel
    constexpr uint8_t BATTERY_ADC_CHANNEL = 0;
}
 
} // namespace Config
 